<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Prueba_Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>5</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>85fd7ed4-6fa7-4f62-b7fb-2ec611e9f008</testSuiteGuid>
   <testCaseLink>
      <guid>0c949b67-a1a6-448b-a9fd-49369d68c491</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GNP/PORTAL/Prueba</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>33b47d39-60b0-43ae-af52-ee8be34dacb4</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Datos</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>33b47d39-60b0-43ae-af52-ee8be34dacb4</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>fecf9b23-1d9f-47bc-8188-bbb07920faf9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>33b47d39-60b0-43ae-af52-ee8be34dacb4</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>0ea8bde0-c5b2-435a-819a-34700c0b8498</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
