<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>USERS_LOGIN_PERFIL</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>202fbf63-cdab-489e-ae4b-37edb6b25cb6</testSuiteGuid>
   <testCaseLink>
      <guid>9c842aba-7b0b-4fa8-8636-e396e8772031</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GNP/PORTAL/GNP_PORTAL_LOGIN _PERFIL</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>477e6706-f7cb-4f53-9397-e0e0f36c2569</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value>1-1</value>
         </iterationEntity>
         <testDataId>Data Files/Usuarios2</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>477e6706-f7cb-4f53-9397-e0e0f36c2569</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>usuario</value>
         <variableId>3498044b-a065-4654-b247-8d00a9162d04</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>477e6706-f7cb-4f53-9397-e0e0f36c2569</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>pass</value>
         <variableId>39724fa2-aa7e-46ef-9cbd-720488ced565</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
