<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>USERS_LOGIN</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>83b0311e-a85c-4cb8-822e-3c6c7a5a7848</testSuiteGuid>
   <testCaseLink>
      <guid>4b139f04-b110-4fd8-bb85-0f9ad9db8f3d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>''</defaultValue>
         <description></description>
         <id>36c06257-e0d9-4e4c-ba60-8dc975a801e3</id>
         <masked>false</masked>
         <name>usuario</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/GNP/PORTAL/GNP_PORTAL_LOGIN</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>0b4280c3-deff-40be-a90a-a38721e66129</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Usuarios</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>0b4280c3-deff-40be-a90a-a38721e66129</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>usuario</value>
         <variableId>36c06257-e0d9-4e4c-ba60-8dc975a801e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0b4280c3-deff-40be-a90a-a38721e66129</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>pass</value>
         <variableId>7bd7336e-6165-47a7-8380-b5619e5a877e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
