<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Mi Plan de Carrera</name>
   <tag></tag>
   <elementGuidId>91fde2d9-4e73-4ab3-adc3-2ed4d142ec4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;art-main&quot;]/nav/div/ul/li[1]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.separator</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a663f96d-e3a8-47e7-b765-fd1b2ef2f689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>separator</value>
      <webElementGuid>6d267064-6310-4183-ae70-bf823d373c4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#?rand=0.13456301276495242</value>
      <webElementGuid>1d927e67-1698-453e-be1c-3cbe60ee5c64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mi Plan de Carrera</value>
      <webElementGuid>c1618e7d-b56d-451e-90bc-d299173866f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;art-main&quot;)/nav[@class=&quot;art-nav desktop-nav&quot;]/div[@class=&quot;art-nav-inner&quot;]/ul[@class=&quot;art-hmenu&quot;]/li[@class=&quot;item-664 deeper parent&quot;]/a[@class=&quot;separator&quot;]</value>
      <webElementGuid>e0cb3a2c-8f8f-42da-a5e2-7414340670ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='art-main']/nav/div/ul/li/a</value>
      <webElementGuid>94b4d44c-e397-48c9-849c-e23833eb2f65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Mi Plan de Carrera')]</value>
      <webElementGuid>433834b9-d05c-4eed-8ed8-810d59fc9fd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perfil'])[1]/following::a[2]</value>
      <webElementGuid>d0d306e9-6cbe-40fa-a892-7edb9f21e7f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Biaani# Gerente Desarrollo Aspirante'])[1]/following::a[3]</value>
      <webElementGuid>fb565483-d227-438c-a5a4-1f474b9c6179</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ABC del Agente'])[1]/preceding::a[1]</value>
      <webElementGuid>c3efdff9-926c-4a8f-ba9f-6fc2a3b963db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inducción a GNP'])[1]/preceding::a[2]</value>
      <webElementGuid>31a47339-a592-4d51-a7c3-8c1da18f43b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mi Plan de Carrera']/parent::*</value>
      <webElementGuid>5305c890-7b5b-4cf3-8d88-37ecf6c785bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#?rand=0.13456301276495242')]</value>
      <webElementGuid>d591fb2f-bf58-4ff2-8b72-284d0957ab3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>cf8d4953-5a33-4efe-adbb-18990a6be693</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#?rand=0.13456301276495242' and (text() = 'Mi Plan de Carrera' or . = 'Mi Plan de Carrera')]</value>
      <webElementGuid>614ac5a7-4d9a-4b0f-8380-f1f7196cbce7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
