<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Boton_busqueda</name>
   <tag></tag>
   <elementGuidId>94306c44-6a0c-4c8b-88c0-440edfc97837</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.art-search-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>440b6753-6828-4394-bf72-296f7de1363f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>ec2db8e6-d2a2-456c-a780-3fba26121c2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>art-search-button</value>
      <webElementGuid>d4f52d6c-3bbe-4a28-8755-ae819ed7acdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;art-main&quot;)/header[@class=&quot;art-header&quot;]/div[@class=&quot;notificaciones&quot;]/div[@class=&quot;notificaciones-content&quot;]/div[@class=&quot;art-textblock art-object227400126&quot;]/form[@class=&quot;art-search&quot;]/input[@class=&quot;art-search-button&quot;]</value>
      <webElementGuid>e992958d-57c6-4429-b738-6df32bc3db1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[2]</value>
      <webElementGuid>2c612468-4c8d-49bf-bb12-c06052726798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='art-main']/header/div[2]/div/div/form/input[6]</value>
      <webElementGuid>b4f4f6b0-1aab-43f1-b2ef-757da7214822</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[6]</value>
      <webElementGuid>1db043bf-90b4-41c1-8fe9-d99a28504f3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>b4f19046-b810-425b-87d4-de39e6b1fb17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
