<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Boton_busqueda</name>
   <tag></tag>
   <elementGuidId>94306c44-6a0c-4c8b-88c0-440edfc97837</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.art-search-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0a27ba06-bbe3-4c07-8cf2-d6ddb88fe24a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>65227194-c289-4e35-99de-e3f18420c0f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>art-search-button</value>
      <webElementGuid>8135bfc6-b998-47ce-8328-9e697c472323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;art-main&quot;)/header[@class=&quot;art-header&quot;]/div[@class=&quot;notificaciones&quot;]/div[@class=&quot;notificaciones-content&quot;]/div[@class=&quot;art-textblock art-object227400126&quot;]/form[@class=&quot;art-search&quot;]/input[@class=&quot;art-search-button&quot;]</value>
      <webElementGuid>afa1feb7-419b-4f39-af03-32dc53688c33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[2]</value>
      <webElementGuid>1a9b4474-fb99-4c40-b0bc-b93e7016ecf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='art-main']/header/div[2]/div/div/form/input[6]</value>
      <webElementGuid>718ed00e-bc2f-4454-b90f-b990debc6d25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[6]</value>
      <webElementGuid>e3cf67fb-4523-4a8d-a2a0-7ce813e14be7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>5c9c1394-5556-4437-95ed-c8cb4558348b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
