<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Biaani Figura de Promocin_searchword</name>
   <tag></tag>
   <elementGuidId>370fb01d-1487-46cc-8dee-dd6ca9de88cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;searchword&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='searchword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9eabebc1-6575-461d-8370-5ecd9ee1a391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f0953505-7288-4ae8-a77c-95e536bbd1d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>searchword</value>
      <webElementGuid>961879d1-9b85-4859-9618-3666c57a138c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;art-main&quot;)/header[@class=&quot;art-header&quot;]/div[@class=&quot;notificaciones&quot;]/div[@class=&quot;notificaciones-content&quot;]/div[@class=&quot;art-textblock art-object227400126&quot;]/form[@class=&quot;art-search&quot;]/input[1]</value>
      <webElementGuid>a223567d-46f3-4b11-a9c7-b9f453c4751c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='searchword']</value>
      <webElementGuid>0fcea0c4-090d-46f5-8c67-c6c3fa9c03e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='art-main']/header/div[2]/div/div/form/input</value>
      <webElementGuid>f8e15529-c2ed-405b-8269-8d2c496b7d87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>6e1b3770-f8cc-4fa6-bd05-3e37971b937c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'searchword']</value>
      <webElementGuid>d895ef04-5a03-459d-bdc5-1f32597eb18a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
