<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Mi Plan de Carrera</name>
   <tag></tag>
   <elementGuidId>dd23eea0-0031-470d-9c95-c8d6e091c233</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '#?rand=0.3292674549533352' and (text() = 'Mi Plan de Carrera' or . = 'Mi Plan de Carrera')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;art-main&quot;]/nav/div/ul/li[1]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.separator</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>97e3b928-903f-41af-9bdc-c6fc054eeb8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>separator</value>
      <webElementGuid>02213d3a-2a61-4e5b-8d98-b40bc483a3f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#?rand=0.3292674549533352</value>
      <webElementGuid>c65b41fc-8fc6-41b2-b8d3-1846f62a5735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mi Plan de Carrera</value>
      <webElementGuid>1229cbae-e3d5-4bed-a655-eca0dd0eec27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;art-main&quot;)/nav[@class=&quot;art-nav desktop-nav&quot;]/div[@class=&quot;art-nav-inner&quot;]/ul[@class=&quot;art-hmenu&quot;]/li[@class=&quot;item-664 deeper parent&quot;]/a[@class=&quot;separator&quot;]</value>
      <webElementGuid>93a62d3f-7ed3-4760-b2aa-fc90cd48c238</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='art-main']/nav/div/ul/li/a</value>
      <webElementGuid>6dd61ec9-68eb-472e-9243-a7556de5477f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Mi Plan de Carrera')]</value>
      <webElementGuid>f0d2fcde-e7d3-4712-9823-23f0cf070e86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perfil'])[1]/following::a[2]</value>
      <webElementGuid>3fd0cd57-91b1-4ffa-a1de-041e9de25b62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Biaani# Gerente Desarrollo Aspirante'])[1]/following::a[3]</value>
      <webElementGuid>a3de5259-5d75-4ec4-817f-4203b5459326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ABC del Agente'])[1]/preceding::a[1]</value>
      <webElementGuid>bc3ebe58-d922-4acc-b136-18dd0be34fd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inducción a GNP'])[1]/preceding::a[2]</value>
      <webElementGuid>7ae8d87a-dc12-4c9a-9a9c-efc2d2b91ba1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mi Plan de Carrera']/parent::*</value>
      <webElementGuid>e748ef29-550d-4341-9ec4-bc4b5418c7ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#?rand=0.3292674549533352')]</value>
      <webElementGuid>fee3d263-9bde-4c5b-9c7c-0aeb0bd748e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>81c4b591-adee-4285-8cb8-9ab2aad96baf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#?rand=0.3292674549533352' and (text() = 'Mi Plan de Carrera' or . = 'Mi Plan de Carrera')]</value>
      <webElementGuid>9a3d16bd-1c63-4eec-ab53-d3c6597aa792</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
